version: "3"
services:
  composer_install:
    image: composer
    volumes:
      - ./:/app
    command: composer install

  web:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    links:
      - php-fpm

  php-fpm:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    env_file:
    - .env

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pwmanager
    ports:
      - "8080:3306"
    volumes:
      - ./db-schema:/docker-entrypoint-initdb.d

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
