version: "3"
services:
  composer_install:
    image: composer
    volumes:
      - ./:/app
    command: composer install

  web:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7999:80
    links:
      - php-fpm

  php-fpm:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
    - HOST
    - DATABASE
    - USERNAME
    - PASSWORD
    - PORT