version: "3"
services:
  composer_install:
    container_name: composer_install
    image: composer
    volumes:
      - ./:/app
    command: composer install

  web:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000
    ports:
      - 7999:8000