version: "3"
services:
  composer_install:
    container_name: composer_install
    image: composer
    volumes:
      - ./:/app
    command: composer install

  web:
    depends_on:
      - composer_install
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000
    ports:
      - 8000:8000
