name: PHPUnit

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  phpunit:
    name: PHPUnit
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3

      - name: Start MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'pwmanager'
          mysql root password: ${{ secrets.MYSQL_PASSWORD }}
          mysql user: ${{ secrets.MYSQL_USER }}
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      - name: Wait for 20 seconds
        run: |
          sleep 20

      - name: Use schmea
        run: |
          mysql --password=root --user=root -h 127.0.0.1 pwmanager < ./db-schema/pwmanager.sql

      - name: Setup PHP, with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mysqli, pdo, pdo_mysql, dom, xml
          tools: composer, phpunit:9
          coverage: xdebug

      - name: Run composer install
        run: composer install --ignore-platform-reqs

      - name: Run PHPUnit
        run: composer test
        env:
          HOST: 127.0.0.1
          DATABASE: pwmanager
          USERNAME: ${{ secrets.MYSQL_USER }}
          PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          PORT: 3306
