name: PHPUnit

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  phpunit:
    name: PHPUnit
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3

      - name: Start MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'pwmanager'
          mysql root password: 'root'
          mysql user: 'root'
          mysql password: 'root'
          container name: mysql-unit


      - name: Wait for 30 seconds
        run: |
          for i in {30..1}; do
          echo "$i"
          sleep 1
          done

      - name: Use schmea
        run: |
          mysql --password=root --user=root -h 127.0.0.1 pwmanager < ./db-schema/pwmanager.sql

      - name: Setup PHP, with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mysqli, pdo, pdo_mysql, dom, xml
          tools: composer, phpunit:9
          coverage: xdebug

      - name: Run composer install
        run: composer install

      - name: Run PHPUnit
        run: composer test
        env:
          HOST: 127.0.0.1
          DATABASE: pwmanager
          USERNAME: root
          PASSWORD: root
          PORT: 3306

      - name: Comment coverage report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ GITHUB_TOKEN }}
          delete-old-comments: true
          title: Coverage Report
        if: github.event_name == 'pull_request'
