name: PHPUnit

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  phpunit:
    name: PHPUnit
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3

      - name: Start MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'pwmanager'
          mysql root password: ${{ secrets.MYSQL_PASSWORD }}
          mysql user: ${{ secrets.MYSQL_USER }}
          mysql password: ${{ secrets.MYSQL_PASSWORD }}
          container name: mysql-unit


      - name: Wait for 20 seconds
        run: |
          sleep 20

      - name: Use schmea
        run: |
          mysql --password=root --user=root -h 127.0.0.1 pwmanager < ./db-schema/pwmanager.sql

      - name: Setup PHP, with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mysqli, pdo, pdo_mysql, dom, xml
          tools: composer, phpunit:9
          coverage: xdebug

      - name: Run composer install
        run: composer install

      - name: Run PHPUnit
        run: composer test
        env:
          HOST: 127.0.0.1
          DATABASE: pwmanager
          USERNAME: ${{ secrets.MYSQL_USER }}
          PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          PORT: 3306

      - name: Delete vendor from coverage && Zip coverage directory
        run: |
          rm -rf coverage/vendor
          zip -9 -r coverage.zip coverage

      - name: Upload PHPUnit coverage report artifact
        uses: actions/upload-artifact@v3
        with:
          name: phpunit-coverage-report
          path: ./coverage.zip

      - name: Comment pull request with PHPUnit coverage report
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ### PHPUnit Coverage Report
            [View report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)
